#!/bin/bash
sudo add-apt-repository -y ppa:mpstark/elementary-tweaks-daily
sudo add-apt-repository -y ppa:birdie-team/daily
sudo add-apt-repository -y ppa:moka/stable
sudo add-apt-repository -y ppa:numix/ppa
apt-get -y update && sudo apt-get upgrade 
sudo apt -y -qq install elementary-tweaks
sudo apt -y -qq install moka-gtk-theme
sudo apt -y -qq install numix-gtk-theme
sudo apt -y -qq install birdie 
 
 
