#!/bin/bash
sudo add-apt-repository -y ppa:versable/elementary-tweaks-isis
sudo add-apt-repository -y ppa:moka/stable
sudo add-apt-repository -y ppa:numix/ppa
apt-get -y update && sudo apt-get upgrade 
sudo apt-get install -y -qq gdebi && 
wget https://github.com/birdieapp/birdie/releases/download/1.1/birdie-granite_1.1.0.r421.pkg20.ubuntu14.04.1_amd64.deb -O birdie64.deb && 

sudo gdebi -n birdie64.deb && rm birdie64.deb
sudo apt-get -y -qq install elementary-tweaks
sudo apt-get -y -qq install moka-gtk-theme
sudo apt-get -y -qq install numix-gtk-theme
 
 
 
 
